OPENAI_BASE_URL="API_BASE_URL"
OPENAI_API_KEY="API_KEY"

# 後端 URL（本地開發用）
BACKEND_URL = "http://localhost:8000"

# AAD 認證設定
AAD_CLIENT_ID="ADD_CLIENT_ID"
AAD_TENANT_ID="ADD_TENANT_ID"
AAD_CLIENT_SECRET="ADD_CLIENT_SECRET"
